// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/teleghost.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PacketType определяет тип пакета
type PacketType int32

const (
	PacketType_PACKET_TYPE_UNSPECIFIED PacketType = 0
	PacketType_HEARTBEAT               PacketType = 1 // Keep-alive сигнал
	PacketType_TEXT_MESSAGE            PacketType = 2 // Текстовое сообщение
	PacketType_PROFILE_UPDATE          PacketType = 3 // Обновление профиля
	PacketType_HANDSHAKE               PacketType = 4 // Рукопожатие для установки соединения
	PacketType_MESSAGE_EDIT            PacketType = 5 // Редактирование сообщения
	PacketType_MESSAGE_DELETE          PacketType = 6 // Удаление сообщения
	PacketType_PROFILE_REQUEST         PacketType = 7 // Запрос обновления профиля
	PacketType_FILE_OFFER              PacketType = 8 // Предложение файла
	PacketType_FILE_RESPONSE           PacketType = 9 // Ответ на предложение
)

// Enum value maps for PacketType.
var (
	PacketType_name = map[int32]string{
		0: "PACKET_TYPE_UNSPECIFIED",
		1: "HEARTBEAT",
		2: "TEXT_MESSAGE",
		3: "PROFILE_UPDATE",
		4: "HANDSHAKE",
		5: "MESSAGE_EDIT",
		6: "MESSAGE_DELETE",
		7: "PROFILE_REQUEST",
		8: "FILE_OFFER",
		9: "FILE_RESPONSE",
	}
	PacketType_value = map[string]int32{
		"PACKET_TYPE_UNSPECIFIED": 0,
		"HEARTBEAT":               1,
		"TEXT_MESSAGE":            2,
		"PROFILE_UPDATE":          3,
		"HANDSHAKE":               4,
		"MESSAGE_EDIT":            5,
		"MESSAGE_DELETE":          6,
		"PROFILE_REQUEST":         7,
		"FILE_OFFER":              8,
		"FILE_RESPONSE":           9,
	}
)

func (x PacketType) Enum() *PacketType {
	p := new(PacketType)
	*p = x
	return p
}

func (x PacketType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PacketType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_teleghost_proto_enumTypes[0].Descriptor()
}

func (PacketType) Type() protoreflect.EnumType {
	return &file_proto_teleghost_proto_enumTypes[0]
}

func (x PacketType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PacketType.Descriptor instead.
func (PacketType) EnumDescriptor() ([]byte, []int) {
	return file_proto_teleghost_proto_rawDescGZIP(), []int{0}
}

// Packet — универсальная обёртка для всех сообщений в сети
type Packet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Версия протокола для обратной совместимости
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Тип содержимого пакета
	Type PacketType `protobuf:"varint,2,opt,name=type,proto3,enum=teleghost.PacketType" json:"type,omitempty"`
	// Публичный ключ отправителя (Ed25519, 32 bytes)
	SenderPubKey []byte `protobuf:"bytes,3,opt,name=sender_pub_key,json=senderPubKey,proto3" json:"sender_pub_key,omitempty"`
	// Подпись payload (Ed25519 signature, 64 bytes)
	Signature []byte `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	// Зашифрованное/сериализованное содержимое (в зависимости от type)
	Payload       []byte `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_proto_teleghost_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teleghost_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_proto_teleghost_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Packet) GetType() PacketType {
	if x != nil {
		return x.Type
	}
	return PacketType_PACKET_TYPE_UNSPECIFIED
}

func (x *Packet) GetSenderPubKey() []byte {
	if x != nil {
		return x.SenderPubKey
	}
	return nil
}

func (x *Packet) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Packet) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Attachment — вложение к сообщению (изображение, файл)
type Attachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`                                      // Данные файла
	IsCompressed  bool                   `protobuf:"varint,6,opt,name=is_compressed,json=isCompressed,proto3" json:"is_compressed,omitempty"` // true если это сжатая версия
	Width         int32                  `protobuf:"varint,7,opt,name=width,proto3" json:"width,omitempty"`                                   // Ширина (для изображений)
	Height        int32                  `protobuf:"varint,8,opt,name=height,proto3" json:"height,omitempty"`                                 // Высота (для изображений)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_proto_teleghost_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teleghost_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_proto_teleghost_proto_rawDescGZIP(), []int{1}
}

func (x *Attachment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Attachment) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Attachment) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Attachment) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Attachment) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Attachment) GetIsCompressed() bool {
	if x != nil {
		return x.IsCompressed
	}
	return false
}

func (x *Attachment) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Attachment) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// TextMessage — текстовое сообщение в чате
type TextMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Уникальный ID чата (обычно hash публичных ключей обоих участников)
	ChatId string `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	// Содержимое сообщения (UTF-8)
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// Unix timestamp в миллисекундах
	Timestamp int64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Уникальный ID сообщения (UUID)
	MessageId string `protobuf:"bytes,4,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Вложения
	Attachments []*Attachment `protobuf:"bytes,5,rep,name=attachments,proto3" json:"attachments,omitempty"`
	// ID сообщения, на которое это ответ (опционально)
	ReplyToId     string `protobuf:"bytes,6,opt,name=reply_to_id,json=replyToId,proto3" json:"reply_to_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextMessage) Reset() {
	*x = TextMessage{}
	mi := &file_proto_teleghost_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextMessage) ProtoMessage() {}

func (x *TextMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teleghost_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextMessage.ProtoReflect.Descriptor instead.
func (*TextMessage) Descriptor() ([]byte, []int) {
	return file_proto_teleghost_proto_rawDescGZIP(), []int{2}
}

func (x *TextMessage) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *TextMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TextMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TextMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *TextMessage) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *TextMessage) GetReplyToId() string {
	if x != nil {
		return x.ReplyToId
	}
	return ""
}

// ProfileUpdate — обновление профиля пользователя
type ProfileUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Никнейм пользователя (max 64 символа)
	Nickname string `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// Описание/био (max 256 символов)
	Bio string `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	// Аватар (сжатое изображение, max 64KB, WebP/JPEG)
	Avatar        []byte `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileUpdate) Reset() {
	*x = ProfileUpdate{}
	mi := &file_proto_teleghost_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileUpdate) ProtoMessage() {}

func (x *ProfileUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teleghost_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileUpdate.ProtoReflect.Descriptor instead.
func (*ProfileUpdate) Descriptor() ([]byte, []int) {
	return file_proto_teleghost_proto_rawDescGZIP(), []int{3}
}

func (x *ProfileUpdate) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ProfileUpdate) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *ProfileUpdate) GetAvatar() []byte {
	if x != nil {
		return x.Avatar
	}
	return nil
}

// Handshake — начало сессии между двумя пирами
type Handshake struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Публичный ключ инициатора
	InitiatorPubKey []byte `protobuf:"bytes,1,opt,name=initiator_pub_key,json=initiatorPubKey,proto3" json:"initiator_pub_key,omitempty"`
	// Временный ключ для ECDH (X25519)
	EphemeralPubKey []byte `protobuf:"bytes,2,opt,name=ephemeral_pub_key,json=ephemeralPubKey,proto3" json:"ephemeral_pub_key,omitempty"`
	// Nonce для предотвращения replay атак
	Nonce []byte `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Timestamp для проверки свежести
	Timestamp int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Никнейм отправителя (для отображения в UI)
	Nickname string `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// I2P адрес отправителя (для обратной связи)
	I2PAddress string `protobuf:"bytes,6,opt,name=i2p_address,json=i2pAddress,proto3" json:"i2p_address,omitempty"`
	// Аватар отправителя (сжатое изображение)
	Avatar        []byte `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Handshake) Reset() {
	*x = Handshake{}
	mi := &file_proto_teleghost_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handshake) ProtoMessage() {}

func (x *Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teleghost_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handshake.ProtoReflect.Descriptor instead.
func (*Handshake) Descriptor() ([]byte, []int) {
	return file_proto_teleghost_proto_rawDescGZIP(), []int{4}
}

func (x *Handshake) GetInitiatorPubKey() []byte {
	if x != nil {
		return x.InitiatorPubKey
	}
	return nil
}

func (x *Handshake) GetEphemeralPubKey() []byte {
	if x != nil {
		return x.EphemeralPubKey
	}
	return nil
}

func (x *Handshake) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *Handshake) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Handshake) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Handshake) GetI2PAddress() string {
	if x != nil {
		return x.I2PAddress
	}
	return ""
}

func (x *Handshake) GetAvatar() []byte {
	if x != nil {
		return x.Avatar
	}
	return nil
}

// MessageEdit — редактирование существующего сообщения
type MessageEdit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID редактируемого сообщения
	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Новое содержимое сообщения
	NewContent string `protobuf:"bytes,2,opt,name=new_content,json=newContent,proto3" json:"new_content,omitempty"`
	// Timestamp редактирования
	Timestamp int64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// ID чата (для маршрутизации)
	ChatId        string `protobuf:"bytes,4,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageEdit) Reset() {
	*x = MessageEdit{}
	mi := &file_proto_teleghost_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEdit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEdit) ProtoMessage() {}

func (x *MessageEdit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teleghost_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEdit.ProtoReflect.Descriptor instead.
func (*MessageEdit) Descriptor() ([]byte, []int) {
	return file_proto_teleghost_proto_rawDescGZIP(), []int{5}
}

func (x *MessageEdit) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageEdit) GetNewContent() string {
	if x != nil {
		return x.NewContent
	}
	return ""
}

func (x *MessageEdit) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MessageEdit) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

// MessageDelete — удаление сообщения
type MessageDelete struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID удаляемого сообщения
	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Timestamp удаления
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// ID чата (для маршрутизации)
	ChatId string `protobuf:"bytes,3,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	// Удалить у всех (true) или только локально (false)
	DeleteForAll  bool `protobuf:"varint,4,opt,name=delete_for_all,json=deleteForAll,proto3" json:"delete_for_all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageDelete) Reset() {
	*x = MessageDelete{}
	mi := &file_proto_teleghost_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageDelete) ProtoMessage() {}

func (x *MessageDelete) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teleghost_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageDelete.ProtoReflect.Descriptor instead.
func (*MessageDelete) Descriptor() ([]byte, []int) {
	return file_proto_teleghost_proto_rawDescGZIP(), []int{6}
}

func (x *MessageDelete) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageDelete) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MessageDelete) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *MessageDelete) GetDeleteForAll() bool {
	if x != nil {
		return x.DeleteForAll
	}
	return false
}

// FileOffer — предложение отправки файлов (для подтверждения)
type FileOffer struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MessageId string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Filenames []string               `protobuf:"bytes,2,rep,name=filenames,proto3" json:"filenames,omitempty"`
	TotalSize int64                  `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	FileCount int32                  `protobuf:"varint,4,opt,name=file_count,json=fileCount,proto3" json:"file_count,omitempty"`
	// Можно добавить previews, но пока опустим для простоты
	ChatId        string `protobuf:"bytes,5,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileOffer) Reset() {
	*x = FileOffer{}
	mi := &file_proto_teleghost_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileOffer) ProtoMessage() {}

func (x *FileOffer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teleghost_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileOffer.ProtoReflect.Descriptor instead.
func (*FileOffer) Descriptor() ([]byte, []int) {
	return file_proto_teleghost_proto_rawDescGZIP(), []int{7}
}

func (x *FileOffer) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *FileOffer) GetFilenames() []string {
	if x != nil {
		return x.Filenames
	}
	return nil
}

func (x *FileOffer) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *FileOffer) GetFileCount() int32 {
	if x != nil {
		return x.FileCount
	}
	return 0
}

func (x *FileOffer) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

// FileResponse — ответ на предложение
type FileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ChatId        string                 `protobuf:"bytes,3,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileResponse) Reset() {
	*x = FileResponse{}
	mi := &file_proto_teleghost_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResponse) ProtoMessage() {}

func (x *FileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_teleghost_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResponse.ProtoReflect.Descriptor instead.
func (*FileResponse) Descriptor() ([]byte, []int) {
	return file_proto_teleghost_proto_rawDescGZIP(), []int{8}
}

func (x *FileResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *FileResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *FileResponse) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

var File_proto_teleghost_proto protoreflect.FileDescriptor

const file_proto_teleghost_proto_rawDesc = "" +
	"\n" +
	"\x15proto/teleghost.proto\x12\tteleghost\"\xab\x01\n" +
	"\x06Packet\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.teleghost.PacketTypeR\x04type\x12$\n" +
	"\x0esender_pub_key\x18\x03 \x01(\fR\fsenderPubKey\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\"\xd0\x01\n" +
	"\n" +
	"Attachment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12#\n" +
	"\ris_compressed\x18\x06 \x01(\bR\fisCompressed\x12\x14\n" +
	"\x05width\x18\a \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\b \x01(\x05R\x06height\"\xd6\x01\n" +
	"\vTextMessage\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"message_id\x18\x04 \x01(\tR\tmessageId\x127\n" +
	"\vattachments\x18\x05 \x03(\v2\x15.teleghost.AttachmentR\vattachments\x12\x1e\n" +
	"\vreply_to_id\x18\x06 \x01(\tR\treplyToId\"U\n" +
	"\rProfileUpdate\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x10\n" +
	"\x03bio\x18\x02 \x01(\tR\x03bio\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\fR\x06avatar\"\xec\x01\n" +
	"\tHandshake\x12*\n" +
	"\x11initiator_pub_key\x18\x01 \x01(\fR\x0finitiatorPubKey\x12*\n" +
	"\x11ephemeral_pub_key\x18\x02 \x01(\fR\x0fephemeralPubKey\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\fR\x05nonce\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\bnickname\x18\x05 \x01(\tR\bnickname\x12\x1f\n" +
	"\vi2p_address\x18\x06 \x01(\tR\n" +
	"i2pAddress\x12\x16\n" +
	"\x06avatar\x18\a \x01(\fR\x06avatar\"\x84\x01\n" +
	"\vMessageEdit\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1f\n" +
	"\vnew_content\x18\x02 \x01(\tR\n" +
	"newContent\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x17\n" +
	"\achat_id\x18\x04 \x01(\tR\x06chatId\"\x8b\x01\n" +
	"\rMessageDelete\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x17\n" +
	"\achat_id\x18\x03 \x01(\tR\x06chatId\x12$\n" +
	"\x0edelete_for_all\x18\x04 \x01(\bR\fdeleteForAll\"\x9f\x01\n" +
	"\tFileOffer\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1c\n" +
	"\tfilenames\x18\x02 \x03(\tR\tfilenames\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x03R\ttotalSize\x12\x1d\n" +
	"\n" +
	"file_count\x18\x04 \x01(\x05R\tfileCount\x12\x17\n" +
	"\achat_id\x18\x05 \x01(\tR\x06chatId\"b\n" +
	"\fFileResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x17\n" +
	"\achat_id\x18\x03 \x01(\tR\x06chatId*\xcb\x01\n" +
	"\n" +
	"PacketType\x12\x1b\n" +
	"\x17PACKET_TYPE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tHEARTBEAT\x10\x01\x12\x10\n" +
	"\fTEXT_MESSAGE\x10\x02\x12\x12\n" +
	"\x0ePROFILE_UPDATE\x10\x03\x12\r\n" +
	"\tHANDSHAKE\x10\x04\x12\x10\n" +
	"\fMESSAGE_EDIT\x10\x05\x12\x12\n" +
	"\x0eMESSAGE_DELETE\x10\x06\x12\x13\n" +
	"\x0fPROFILE_REQUEST\x10\a\x12\x0e\n" +
	"\n" +
	"FILE_OFFER\x10\b\x12\x11\n" +
	"\rFILE_RESPONSE\x10\tB+Z)github.com/teleghost/internal/proto;protob\x06proto3"

var (
	file_proto_teleghost_proto_rawDescOnce sync.Once
	file_proto_teleghost_proto_rawDescData []byte
)

func file_proto_teleghost_proto_rawDescGZIP() []byte {
	file_proto_teleghost_proto_rawDescOnce.Do(func() {
		file_proto_teleghost_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_teleghost_proto_rawDesc), len(file_proto_teleghost_proto_rawDesc)))
	})
	return file_proto_teleghost_proto_rawDescData
}

var file_proto_teleghost_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_teleghost_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_teleghost_proto_goTypes = []any{
	(PacketType)(0),       // 0: teleghost.PacketType
	(*Packet)(nil),        // 1: teleghost.Packet
	(*Attachment)(nil),    // 2: teleghost.Attachment
	(*TextMessage)(nil),   // 3: teleghost.TextMessage
	(*ProfileUpdate)(nil), // 4: teleghost.ProfileUpdate
	(*Handshake)(nil),     // 5: teleghost.Handshake
	(*MessageEdit)(nil),   // 6: teleghost.MessageEdit
	(*MessageDelete)(nil), // 7: teleghost.MessageDelete
	(*FileOffer)(nil),     // 8: teleghost.FileOffer
	(*FileResponse)(nil),  // 9: teleghost.FileResponse
}
var file_proto_teleghost_proto_depIdxs = []int32{
	0, // 0: teleghost.Packet.type:type_name -> teleghost.PacketType
	2, // 1: teleghost.TextMessage.attachments:type_name -> teleghost.Attachment
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_teleghost_proto_init() }
func file_proto_teleghost_proto_init() {
	if File_proto_teleghost_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_teleghost_proto_rawDesc), len(file_proto_teleghost_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_teleghost_proto_goTypes,
		DependencyIndexes: file_proto_teleghost_proto_depIdxs,
		EnumInfos:         file_proto_teleghost_proto_enumTypes,
		MessageInfos:      file_proto_teleghost_proto_msgTypes,
	}.Build()
	File_proto_teleghost_proto = out.File
	file_proto_teleghost_proto_goTypes = nil
	file_proto_teleghost_proto_depIdxs = nil
}
