linters-settings:
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 40
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 5
  misspell:
    locale: US
  lll:
    line-length: 250
  goimports:
    local-prefixes: github.com/kiktor12358/TeleGhost

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gocyclo
    - goconst
    - misspell
    - lll
    - unparam
    - nakedret
    - prealloc
    - whitespace
    - bodyclose
    - noctx

run:
  timeout: 5m
  tests: true

issues:
  exclude-dirs:
    - vendor
    - android
    - frontend/node_modules
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocyclo
    - linters:
        - errcheck
      text: "tx.Rollback"
    - linters:
        - errcheck
      text: "os.MkdirAll"
