// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AcceptFileTransfer(arg1:string):Promise<void>;

export function AddChatToFolder(arg1:string,arg2:string):Promise<void>;

export function AddContact(arg1:string,arg2:string):Promise<main.ContactInfo>;

export function AddContactFromClipboard():Promise<main.ContactInfo>;

export function CopyImageToClipboard(arg1:string):Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function CreateAccount():Promise<string>;

export function CreateFolder(arg1:string,arg2:string):Promise<string>;

export function DeclineFileTransfer(arg1:string):Promise<void>;

export function DeleteContact(arg1:string):Promise<void>;

export function DeleteFolder(arg1:string):Promise<void>;

export function DeleteMessage(arg1:string):Promise<void>;

export function DeleteMessageForAll(arg1:string):Promise<void>;

export function EditMessage(arg1:string,arg2:string):Promise<void>;

export function GetContacts():Promise<Array<main.ContactInfo>>;

export function GetFileBase64(arg1:string):Promise<string>;

export function GetFolders():Promise<Array<main.FolderInfo>>;

export function GetImageThumbnail(arg1:string,arg2:number,arg3:number):Promise<string>;

export function GetMessageByID(arg1:string):Promise<main.MessageInfo>;

export function GetMessages(arg1:string,arg2:number,arg3:number):Promise<Array<main.MessageInfo>>;

export function GetMyDestination():Promise<string>;

export function GetMyInfo():Promise<main.UserInfo>;

export function GetNetworkStatus():Promise<string>;

export function GetRouterSettings():Promise<main.RouterSettings>;

export function Login(arg1:string):Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function QuitApp():Promise<void>;

export function RemoveChatFromFolder(arg1:string,arg2:string):Promise<void>;

export function RequestProfileUpdate(arg1:string):Promise<void>;

export function SaveRouterSettings(arg1:main.RouterSettings):Promise<void>;

export function SaveTempImage(arg1:string,arg2:string):Promise<string>;

export function SelectFiles():Promise<Array<string>>;

export function SendFileMessage(arg1:string,arg2:string,arg3:Array<string>,arg4:boolean):Promise<void>;

export function SendText(arg1:string,arg2:string):Promise<void>;

export function ShowInFolder(arg1:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function UpdateFolder(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateMyProfile(arg1:string,arg2:string,arg3:string):Promise<void>;
