// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptFileTransfer(arg1) {
  return window['go']['main']['App']['AcceptFileTransfer'](arg1);
}

export function AddChatToFolder(arg1, arg2) {
  return window['go']['main']['App']['AddChatToFolder'](arg1, arg2);
}

export function AddContact(arg1, arg2) {
  return window['go']['main']['App']['AddContact'](arg1, arg2);
}

export function AddContactFromClipboard() {
  return window['go']['main']['App']['AddContactFromClipboard']();
}

export function CopyImageToClipboard(arg1) {
  return window['go']['main']['App']['CopyImageToClipboard'](arg1);
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function CreateAccount() {
  return window['go']['main']['App']['CreateAccount']();
}

export function CreateFolder(arg1, arg2) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2);
}

export function DeclineFileTransfer(arg1) {
  return window['go']['main']['App']['DeclineFileTransfer'](arg1);
}

export function DeleteContact(arg1) {
  return window['go']['main']['App']['DeleteContact'](arg1);
}

export function DeleteFolder(arg1) {
  return window['go']['main']['App']['DeleteFolder'](arg1);
}

export function DeleteMessage(arg1) {
  return window['go']['main']['App']['DeleteMessage'](arg1);
}

export function DeleteMessageForAll(arg1) {
  return window['go']['main']['App']['DeleteMessageForAll'](arg1);
}

export function EditMessage(arg1, arg2) {
  return window['go']['main']['App']['EditMessage'](arg1, arg2);
}

export function GetContacts() {
  return window['go']['main']['App']['GetContacts']();
}

export function GetFileBase64(arg1) {
  return window['go']['main']['App']['GetFileBase64'](arg1);
}

export function GetFolders() {
  return window['go']['main']['App']['GetFolders']();
}

export function GetImageThumbnail(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetImageThumbnail'](arg1, arg2, arg3);
}

export function GetMessageByID(arg1) {
  return window['go']['main']['App']['GetMessageByID'](arg1);
}

export function GetMessages(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetMessages'](arg1, arg2, arg3);
}

export function GetMyDestination() {
  return window['go']['main']['App']['GetMyDestination']();
}

export function GetMyInfo() {
  return window['go']['main']['App']['GetMyInfo']();
}

export function GetNetworkStatus() {
  return window['go']['main']['App']['GetNetworkStatus']();
}

export function GetRouterSettings() {
  return window['go']['main']['App']['GetRouterSettings']();
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function RemoveChatFromFolder(arg1, arg2) {
  return window['go']['main']['App']['RemoveChatFromFolder'](arg1, arg2);
}

export function RequestProfileUpdate(arg1) {
  return window['go']['main']['App']['RequestProfileUpdate'](arg1);
}

export function SaveRouterSettings(arg1) {
  return window['go']['main']['App']['SaveRouterSettings'](arg1);
}

export function SaveTempImage(arg1, arg2) {
  return window['go']['main']['App']['SaveTempImage'](arg1, arg2);
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function SendFileMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendFileMessage'](arg1, arg2, arg3, arg4);
}

export function SendText(arg1, arg2) {
  return window['go']['main']['App']['SendText'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function UpdateFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateFolder'](arg1, arg2, arg3);
}

export function UpdateMyProfile(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateMyProfile'](arg1, arg2, arg3);
}
