// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddContact(arg1, arg2) {
  return window['go']['main']['App']['AddContact'](arg1, arg2);
}

export function AddContactFromClipboard() {
  return window['go']['main']['App']['AddContactFromClipboard']();
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function CreateAccount() {
  return window['go']['main']['App']['CreateAccount']();
}

export function GetContacts() {
  return window['go']['main']['App']['GetContacts']();
}

export function GetMessages(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetMessages'](arg1, arg2, arg3);
}

export function GetMyDestination() {
  return window['go']['main']['App']['GetMyDestination']();
}

export function GetMyInfo() {
  return window['go']['main']['App']['GetMyInfo']();
}

export function GetNetworkStatus() {
  return window['go']['main']['App']['GetNetworkStatus']();
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function SendText(arg1, arg2) {
  return window['go']['main']['App']['SendText'](arg1, arg2);
}

export function UpdateMyProfile(arg1, arg2) {
  return window['go']['main']['App']['UpdateMyProfile'](arg1, arg2);
}
