// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddChatToFolder(arg1:string,arg2:string):Promise<void>;

export function AddContact(arg1:string,arg2:string):Promise<main.ContactInfo>;

export function AddContactFromClipboard():Promise<main.ContactInfo>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function CreateAccount():Promise<string>;

export function CreateFolder(arg1:string,arg2:string):Promise<string>;

export function DeleteContact(arg1:string):Promise<void>;

export function DeleteFolder(arg1:string):Promise<void>;

export function DeleteMessage(arg1:string):Promise<void>;

export function DeleteMessageForAll(arg1:string):Promise<void>;

export function EditMessage(arg1:string,arg2:string):Promise<void>;

export function GetContacts():Promise<Array<main.ContactInfo>>;

export function GetFolders():Promise<Array<main.FolderInfo>>;

export function GetMessageByID(arg1:string):Promise<main.MessageInfo>;

export function GetMessages(arg1:string,arg2:number,arg3:number):Promise<Array<main.MessageInfo>>;

export function GetMyDestination():Promise<string>;

export function GetMyInfo():Promise<main.UserInfo>;

export function GetNetworkStatus():Promise<string>;

export function Login(arg1:string):Promise<void>;

export function QuitApp():Promise<void>;

export function RemoveChatFromFolder(arg1:string,arg2:string):Promise<void>;

export function SendText(arg1:string,arg2:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function UpdateFolder(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateMyProfile(arg1:string,arg2:string,arg3:string):Promise<void>;
